### ISSUE TITLE
[wallet] Some feature issue of web-wallet

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/aelf-web-wallet#14]
- [x] 1. call the API[POST:api/nodes/info] of aelf-block-api to insert the AElf Node information. when the 
	`rpc_domain: " "`, send transaction will get error message: `{"message":"Validation Failed"}`
![image](https://user-images.githubusercontent.com/45747546/50634314-2cea4e80-0f89-11e9-82fe-043faddcd0a9.png)

- [x] 2. When two chain's symbol is same, cannot display transaction information on the second chain
 
![image](https://user-images.githubusercontent.com/45747546/50634516-dfbaac80-0f89-11e9-878f-965f9a92820e.png)
![image](https://user-images.githubusercontent.com/45747546/50634551-ff51d500-0f89-11e9-9cfe-e82590e943f7.png)

- [x] 3. Failed to import wallet with private key.

- [x] 4. Can't display the failed transaction on transaction list.

- [x] 5. When the password is simple, it will get message "The passwords confirmed error."  need add the other passwords error message.

- [x] 6. In Create wallet, can't disabled the align  
![image](https://user-images.githubusercontent.com/45747546/50634833-c9612080-0f8a-11e9-8dc0-88cb03305a3f.png)

- [x] 7. In Chinese system, the Amount converted money display USD

**Comment by hzz780** [comment]
1.  [P2] Because we can not insert a invalid URL.   I will check the input in API.
2. [Not a bug, but may need fix] Because we do not allow the same symbol & token name. If one of the  symbol, token name, contract address  of a new chain is the same to a record, we do not insert it.
3. [P0] ......
4. [P0]
5. [P1]
6. [Design] Because it means nothing to disagree it after we agree it.
7. [TODO] We only have one Currency Unit now.

@YueZh127

**Comment by hzz780** [comment]
3. Failed to import wallet with private key.
ehhhh, i can not reproduce it..........

**Comment by hzz780** [comment]
3. Failed to import wallet with private key.
ehhhh, i can not reproduce it..........

**Comment by hzz780** [comment]
1. add value check. trim & check http/https
2. done
3. I can not reproduce
4. display now
5. done
6. can cancel now.
7. more Currency Unit[TODO]

util https://github.com/AElfProject/aelf-web-wallet/commit/4a6ce105f8f672275697c4c411f47803429ae85f
